source 'https://rubygems.org'
gem 'rake', '~> 10.0.3'
gem 'pry'
gem 'mongo_mapper', '~> 0.12.0'
gem 'bson_ext', '~> 1.8.2'
gem 'hashie'
gem "sinatra"
gem "tux"
gem "oauth"
gem 'tux'
gem 'oauth'
gem 'bcrypt-ruby', '~> 3.0.1'
gem "sinatra-flash", "~> 0.3.0"